apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sturna-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: sturna-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60