apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sturna-ingress
spec:
  rules:
  - host: sturna.yourcompany.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sturna-api
            port:
              number: 8000