"""Initial models

Revision ID: 0001
Revises: 
Create Date: 2026-05-31

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_class', sa.String(length=32), nullable=False),
    sa.Column('coalition', sa.String(length=32), nullable=True),
    sa.Column('capability_hash', sa.String(length=64), nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('swarm_score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('march_score', sa.Float(), nullable=False),
    sa.Column('bid_confidence', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('cost_per_intent', sa.Float(), nullable=False),
    sa.Column('model_endpoint', sa.String(length=512), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quarantine_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_index('ix_agents_agent_id', 'agents', ['agent_id'], unique=True)
    op.create_index('ix_agents_class_health', 'agents', ['agent_class', 'health_score'], unique=False)
    op.create_index('ix_agents_coalition_status', 'agents', ['coalition', 'status'], unique=False)
    op.create_index('ix_agents_status', 'agents', ['status'], unique=False)
    op.create_index('ix_agents_tier_score', 'agents', ['tier', 'swarm_score'], unique=False)

    op.create_table('shared_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pattern_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_agent_ids', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('source_memory_ids', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_id')
    )
    op.create_index('ix_shared_category_confidence', 'shared_memories', ['category', 'confidence'], unique=False)
    op.create_index('ix_shared_memories_pattern_id', 'shared_memories', ['pattern_id'], unique=True)

    op.create_table('agent_identity_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('token_id', sa.String(length=64), nullable=False),
    sa.Column('reputation_history', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id'),
    sa.UniqueConstraint('token_id')
    )
    op.create_index('ix_agent_identity_registry_agent_id', 'agent_identity_registry', ['agent_id'], unique=True)

    op.create_table('agent_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=False),
    sa.Column('gsar_pass', sa.Boolean(), nullable=False),
    sa.Column('grounding_source', sa.String(length=512), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('intent_id', sa.String(length=64), nullable=True),
    sa.Column('decay_factor', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_memory_ids', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('child_memory_ids', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_memories_agent_id', 'agent_memories', ['agent_id'], unique=False)
    op.create_index('ix_memories_agent_tier', 'agent_memories', ['agent_id', 'tier'], unique=False)
    op.create_index('ix_memories_agent_type', 'agent_memories', ['agent_id', 'memory_type'], unique=False)
    op.create_index('ix_memories_session', 'agent_memories', ['session_id'], unique=False)
    op.create_index('ix_memories_status_decay', 'agent_memories', ['status', 'decay_factor'], unique=False)

    op.create_table('memory_defense_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('probe_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action_taken', sa.String(length=32), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['agent_memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_defense_logs_memory_id', 'memory_defense_logs', ['memory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memory_defense_logs_memory_id', table_name='memory_defense_logs')
    op.drop_table('memory_defense_logs')
    
    op.drop_index('ix_memories_status_decay', table_name='agent_memories')
    op.drop_index('ix_memories_session', table_name='agent_memories')
    op.drop_index('ix_memories_agent_type', table_name='agent_memories')
    op.drop_index('ix_memories_agent_tier', table_name='agent_memories')
    op.drop_index('ix_agent_memories_agent_id', table_name='agent_memories')
    op.drop_table('agent_memories')
    
    op.drop_index('ix_agent_identity_registry_agent_id', table_name='agent_identity_registry')
    op.drop_table('agent_identity_registry')
    
    op.drop_index('ix_shared_category_confidence', table_name='shared_memories')
    op.drop_index('ix_shared_memories_pattern_id', table_name='shared_memories')
    op.drop_table('shared_memories')
    
    op.drop_index('ix_agents_tier_score', table_name='agents')
    op.drop_index('ix_agents_coalition_status', table_name='agents')
    op.drop_index('ix_agents_class_health', table_name='agents')
    op.drop_index('ix_agents_status', table_name='agents')
    op.drop_index('ix_agents_agent_id', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###