// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * SturnaGroth16Verifier.sol
 *
 * Groth16 verifier for the SturnaAuctionCompliance circuit.
 * Generated from: snarkjs zkey export solidityverifier circuit_final.zkey verifier.sol
 *
 * Circuit: SturnaAuctionCompliance.circom
 *   - Public signals: [auction_commitment, march_pass, confidence_scaled]
 *   - Constraints: <500K (bn128 / BN254 curve)
 *   - Prover: snarkjs groth16.fullProve()
 *
 * Deployment target: zkSync Era Sepolia (chain ID 300)
 *   npx hardhat deploy-zksync --script deploy/deploy-verifier.ts --network zkSyncSepoliaTestnet
 *
 * What this contract verifies (NOT what snarkjs generates — this is the circuit semantics):
 *   1. auction_commitment: SHA-256 of (run_id + winner_bid + coalition_json + HMAC sig)
 *   2. march_pass: 1 = all 3 MARCH gates passed, 0 = failure
 *   3. confidence_scaled: winning agent's declared confidence * 1000 (integer, 0–1000)
 *
 * NOTE: The actual verification key (alpha, beta, gamma, delta, IC) must be replaced
 * with the real values generated from the trusted setup ceremony.
 * Placeholder values below are for ABI/interface reference only.
 */

// Pairing library for BN254 (standard Groth16 verification)
library Pairing {
    struct G1Point {
        uint256 X;
        uint256 Y;
    }
    struct G2Point {
        uint256[2] X;
        uint256[2] Y;
    }

    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        uint256 q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        return G1Point(p.X, q - (p.Y % q));
    }

    function addition(G1Point memory p1, G1Point memory p2)
        internal view returns (G1Point memory r)
    {
        uint256[4] memory input;
        input[0] = p1.X;
        input[1] = p1.Y;
        input[2] = p2.X;
        input[3] = p2.Y;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 6, input, 0x80, r, 0x40)
            switch success case 0 { invalid() }
        }
    }

    function scalar_mul(G1Point memory p, uint256 s)
        internal view returns (G1Point memory r)
    {
        uint256[3] memory input;
        input[0] = p.X;
        input[1] = p.Y;
        input[2] = s;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 7, input, 0x60, r, 0x40)
            switch success case 0 { invalid() }
        }
    }

    function pairing(G1Point[] memory p1, G2Point[] memory p2)
        internal view returns (bool)
    {
        require(p1.length == p2.length, "Pairing: input mismatch");
        uint256 elements = p1.length;
        uint256 inputSize = elements * 6;
        uint256[] memory input = new uint256[](inputSize);
        for (uint256 i = 0; i < elements; i++) {
            input[i * 6 + 0] = p1[i].X;
            input[i * 6 + 1] = p1[i].Y;
            input[i * 6 + 2] = p2[i].X[0];
            input[i * 6 + 3] = p2[i].X[1];
            input[i * 6 + 4] = p2[i].Y[0];
            input[i * 6 + 5] = p2[i].Y[1];
        }
        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(sub(gas(), 2000), 8, add(input, 0x20), mul(inputSize, 0x20), out, 0x20)
            switch success case 0 { invalid() }
        }
        return out[0] != 0;
    }
}

contract SturnaGroth16Verifier {
    using Pairing for *;

    // ── Verification Key (replace with snarkjs-generated values) ─────────────
    // Generated by: snarkjs zkey export verificationkey circuit_final.zkey vk.json
    // Then: snarkjs zkey export solidityverifier circuit_final.zkey verifier.sol

    struct VerifyingKey {
        Pairing.G1Point alpha;
        Pairing.G2Point beta;
        Pairing.G2Point gamma;
        Pairing.G2Point delta;
        Pairing.G1Point[] IC; // IC.length = n_public_inputs + 1
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    function verifyingKey() internal pure returns (VerifyingKey memory vk) {
        // PLACEHOLDER — replace with actual trusted-setup output
        // from `snarkjs zkey export solidityverifier circuit_final.zkey verifier.sol`
        vk.alpha = Pairing.G1Point(
            0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2,
            0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed
        );
        vk.beta = Pairing.G2Point(
            [0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b,
             0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa],
            [0x275dc4a288d1afb3cbb1ac09187524c7db36395df7be3b99e673b13a075a65ec,
             0x1d9befcd05a5323e6da4d435f3b617cdb3af83285c2df711ef39c01571827f9d]
        );
        vk.gamma = Pairing.G2Point(
            [0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2,
             0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed],
            [0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b,
             0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa]
        );
        vk.delta = Pairing.G2Point(
            [0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2,
             0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed],
            [0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b,
             0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa]
        );
        // IC[0]: constant term, IC[1..3]: per-public-input terms
        vk.IC = new Pairing.G1Point[](4);
        vk.IC[0] = Pairing.G1Point(
            0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2,
            0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed
        );
        vk.IC[1] = Pairing.G1Point(
            0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b,
            0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa
        );
        vk.IC[2] = Pairing.G1Point(
            0x275dc4a288d1afb3cbb1ac09187524c7db36395df7be3b99e673b13a075a65ec,
            0x1d9befcd05a5323e6da4d435f3b617cdb3af83285c2df711ef39c01571827f9d
        );
        vk.IC[3] = Pairing.G1Point(
            0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2,
            0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed
        );
    }

    /**
     * @notice Verify a Groth16 proof for the SturnaAuctionCompliance circuit.
     * @param a  Proof.A (G1 point)
     * @param b  Proof.B (G2 point)
     * @param c  Proof.C (G1 point)
     * @param input Public signals: [auction_commitment, march_pass, confidence_scaled]
     * @return bool true if proof is valid
     */
    function verifyProof(
        uint256[2]    calldata a,
        uint256[2][2] calldata b,
        uint256[2]    calldata c,
        uint256[3]    calldata input
    ) external view returns (bool) {
        Proof memory proof;
        proof.A = Pairing.G1Point(a[0], a[1]);
        proof.B = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);
        proof.C = Pairing.G1Point(c[0], c[1]);

        VerifyingKey memory vk = verifyingKey();
        require(vk.IC.length == input.length + 1, "Verifier: public input length mismatch");

        // Compute vk_x = IC[0] + sum(input[i] * IC[i+1])
        Pairing.G1Point memory vk_x = vk.IC[0];
        for (uint256 i = 0; i < input.length; i++) {
            vk_x = Pairing.addition(vk_x, Pairing.scalar_mul(vk.IC[i + 1], input[i]));
        }

        // Check pairing: e(A, B) == e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
        Pairing.G1Point[] memory p1 = new Pairing.G1Point[](4);
        Pairing.G2Point[] memory p2 = new Pairing.G2Point[](4);
        p1[0] = Pairing.negate(proof.A);
        p2[0] = proof.B;
        p1[1] = vk.alpha;
        p2[1] = vk.beta;
        p1[2] = vk_x;
        p2[2] = vk.gamma;
        p1[3] = proof.C;
        p2[3] = vk.delta;

        return Pairing.pairing(p1, p2);
    }
}